### ISSUE TITLE
Get rid of GitLab and provide the assets pre-baked?

### ISSUE THREAD

**Issue by kenmoini** [ansible/workshops#1107]
##### SUMMARY
Looks like the gitlab_server role is having some difficulties around authentication to the GitLab API and thus provisioning the Ansible for Windows workshop is failing.

Scanning through the [workshop curriculum](https://ansible.github.io/workshops/exercises/ansible_windows/) it seems like GitLab is just used for a temporary SCM while the students copy/paste chunks of YAML into files they create?  Not even in a webhook trigger?

Seems pretty heavy on the Git-side of things, we could probably demonstrate Ansible for Windows better if those exercises are truncated.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- exercises
- provisioner

##### ADDITIONAL INFORMATION
Pre-provide all the Ansible YAML assets needed for the workshop, which with that can remove the need for a GitLab server as all the Projects can be served from public hosted GitHub/GitLab repos.

1. This prevents issues around spacing and can speed up workshops by reducing that space-space-space-dash-space debug effort.
2. Providing the assets ready to consume allows additional for exercises to further demonstrate the value of Ansible
3. Time, time, time.  In a virtual-first world 4-6h workshops are tedious and hardly effective.  Pre-providing assets allows for a more easily schedulable workshop event, as well as making it more easy to actually pay attention to and work through.

For an example of such a sort of workshop, check out this revision of an Ansible Workshop: https://learn.kemo.network/workshops/ansible_automation/

That version is a mashup of content from these Ansible workshops, RHGov Ansible workshops, and some custom content to add exercises around additional automation concepts.  With all those exercises, all the content is pre-provided with a rich user experience and the whole workshop can be completed in 2 hours.

Thoughts?

**Comment by cigamit** [comment]
Actually, the users aren't meant to be copy and pasting code, they are to be typing it out.  You don't learn anything by copy and pasting or by using prebuilt assets.  An SCM is an important part of using Tower in a real world environment, the Windows Workshop simulates how they will actually be using Tower.

**Comment by cloin** [comment]
Windows workshop is unique in that I believe it's the only one that uses SCM while SCM is required for AAP. The students' content is only available to execute by committing to SCM.

**Comment by kenmoini** [comment]
@cigamit Yeah, that'd be great, but if you believe users are actually taping out the YAML vs copy/pasting then well, I got a bridge to sell ya lol

Obviously SCM is an important part of workflows in Ansible Tower, can't do much outside of Ad-hoc commands without it eh? Is the goal to show how a user does elementary interactions with a Git repo over and over or to demonstrate the value of Ansible?

My suggestion isn't to get rid of SCM entirely, it's to pre-provide the resources for Tower Projects from a public source.  What makes the Windows workshop any different from the normal RHEL workshop that pre-provides the resources from GitHub?
https://ansible.github.io/workshops/exercises/ansible_rhel/2.3-projects/

**Comment by cigamit** [comment]
Oh, I know there are a few that copy and paste, and some people that are running behind I encourage it for them to catch up, but as the person that wrote the windows workshop and having delivered it to 1000s of people, I can tell you that a majority of them type it out.  I know because I watched them do it (pre-covid) and I helped fixed all the mistakes they made while typing it out.  I even tell them at the beginning of the workshop that while the content is there to showcase how it should look, they will learn it better if they type it out themselves.

The goal is more to get them started using Ansible in a way that makes sense to them and is something they can build on.  If we teach them to import repos with pre-built playbooks, they aren't learning to write Ansible which is the fundamental first step to properly using Ansible.

The RHEL course IMO needs to be completely rewritten from scratch (and for my instant workshops, I am doing that), it doesn't teach Tower as a facility for the automation, its more of an afterthought.

**Comment by cloin** [comment]
I must have just been confused by the title of the issue. The idea with a central SCM was to show a more realistic approach. We can pre-populate the student repos if there's value in that. In order to make changes to the content in the repo however, we'll still have to show how to commit to scm.

One of the primary goals in modifying the original workshop and bringing windows automation into the fold was to have a more AAP focused automation workshop. SCM in the AAP focus is unavoidable.

**Comment by cigamit** [comment]
No from what I gather, he is more talking of dropping the gitlab server completely, and moving to a public pre-populated repo that is a single repo used by all the students (aka, they no longer write playbooks at all).

**Comment by cloin** [comment]
IMO with this workshop type already being one of the least resource consuming workshop types, I think we gain more flexibility by keeping the current architecture including a node reserved for whatever SCM app makes sense (gitlab today). 

There’s a lot of functionality that can be demonstrated with this current setup not just workshop interaction but use case demonstration (things like gitops) that this gitlab node facilitates. 

@kenmoini wete you able to pinpoint the issue with gitlab auth when it’s trying to set the root pw? I wonder if we jus these to grab the latest version of this role.

**Comment by kenmoini** [comment]
@cigamit Woah that's awesome, didn't know you made the workshop, thanks for all your hard work!  I too used to proctor in-person workshops from coast-to-coast, from private customer engagements to packed ballrooms at the Marriott with 80-100 folk - boy that was a blast!  I sure don't miss having to run around the room debugging spaces-related issues though.

Anywho, seems like I struck a nerve, so sorry about that, I'll just continue to maintain my own version and leave the suggestion box alone, closing this out.

@cloin It seems to be an issue with the authentication against the GitLab API in `roles/gitlab-server/tasks/add-user.yml` at the "GitLab Post | Check if root user password is set" task.  Been trying to fix it to help another SA for one of their customers to no avail.  No worries though, we'll work through another avenue to get this rolling 👍

**Comment by ffirg** [comment]
Just to chip in here as well. Used the windows workshop (via RHPDS) for 22 windows admins today. I made it clear they will learn best by typing line by line as it'll focus minds of the task in hand. I like the gitlab implementation as it is a more realistic situation and it would be great to use similar in RHEL/networking as well. I think if there were correct playbooks they could run if they get in a mess would be a good compromise.
