### ISSUE TITLE
wrong code snippet  

### ISSUE THREAD

**Issue by heimdallreport** [ansible/workshops#1370]
### Area

Ansible Red Hat Enterprise Linux Workshop

### Proposed Changes

in the https://aap2.demoredhat.com/exercises/ansible_rhel_90/3-playbook/
---
- name: Check Status
  hosts: node1
  become: true
  vars:
    package: "httpd"

  tasks:
    - name: Check status of  service
      service_facts:
      register: service_state

    - debug:
        var: service_state.ansible_facts.services[".service"].state

need to be changed to: 
---
- name: Check Status
  hosts: node1
  become: true
  vars:
    package: "httpd"

  tasks:
    - name: Check status of  service
      service_facts:

    - debug:
        var: ansible_facts.services["{{ package }}.service"].state

**Comment by IPvSean** [comment]
thank you for finding these @heimdallreport  and @forenkla !!

What happens here is that we render the markdown into the website using Github pages.  The technology "under the hood" is just Jekyll.  Jekyll uses the same templating engine that Ansible does.... so if we don't properly escape a code snippet (or rather just simple YAML) it will try to render it in Jekyll instead of just leaving it alone... and since I didn't actually load any variables for it to render it will render blank.

The way to fix this (as you can see in https://github.com/IPvSean/workshops/commit/f9dec368936a1a7de3c3731fd5a15a5b0abf233e) is to add a {% raw %} and {% endraw %} around the code that contains double {{ stuff }}

Let me know if you catch any other mis-rendered code... it is easy to fix... but we must have missed a couple spots... :( 

Thanks again
