### ISSUE TITLE
RIPU bug in Exercise 1.3

### ISSUE THREAD

**Issue by amysohyanling** [ansible/workshops#2169]
### Problem Summary

![image](https://github.com/user-attachments/assets/f843a226-7c3d-4a89-8bee-3c82f394fbb3)
under the exercise
https://aap2.demoredhat.com/exercises/ansible_ripu/1.3-report/

Having verified you are looking at one of the RHEL8 pet app servers, use the main menu to navigate to Tools > Upgrade Report. This will display the Leapp pre-upgrade report that was generated for the selected host. For example, the report might look like this:

No data to show, please run leapp preupgrade on this machine to continue.

### Issue Type

Bug

### Extra vars file

https://aap2.demoredhat.com/exercises/ansible_ripu/1.3-report/

### Ansible Playbook Output

https://ansible-1.nrh4c.sandbox2313.opentlc.com:9090/@safe8gibbon/leapp

### Ansible Version

-

### Ansible Configuration

-

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

-

**Comment by abenokraitis** [comment]
@heatmiser FYI

**Comment by heatmiser** [comment]
@amysohyanling Based on the screenshot that you provided, it appears that you have not enable `Administrative Access`.
![355306686-f843a226-7c3d-4a89-8bee-3c82f394fbb3](https://github.com/user-attachments/assets/c6f046a3-f1fd-4f66-8d4b-1a74cc757bff)
In order to view the pre-upgrade report, `Administrative Access` must be enabled. The exercise provides instructions on how to accomplish this:
![image](https://github.com/user-attachments/assets/337ca896-3671-4b7f-82fc-a3f13d232d56)
Please revisit the portion of the exercise utilizing the above instructions and once `Administrative Access` is enabled, try to access the pre-upgrade report.

**Comment by abenokraitis** [comment]
Assuming this has been resolved, please re-open if not.
