### ISSUE TITLE
Engine Exercise #2 needs to run playbook and check syntax

### ISSUE THREAD

**Issue by rcpavlicek** [ansible/workshops#318]
After constructing their first playbook, the student is NEVER instructed to run the playbook, as the workshop used to do.  Until they try running the playbook, they will have no idea if they constructed it correctly.  In my history of giving these workshops, running the first playbook successfully is one of the most intense exercises of the day.  They should also be introduced to the command to check the syntax of the playbook.  Both running and checking syntax used to be in earlier versions of the workshop. I had to give oral instructions on running the first playbook in the workshop I delivered yesterday.

**Comment by liquidat** [comment]
The playbook is run in [exercise 4, step 2](https://github.com/ansible/workshops/blob/master/exercises/ansible_engine/4-runplaybook/README.md#step-2):

> Step 2:
> Run your playbook
> 
> ansible-playbook -i ~/lightbulb/lessons/lab_inventory/student##-instances.txt site.yml

This was also the case with the [old lightbulb guides](https://github.com/ansible/lightbulb/tree/master/guides/ansible_engine/3-variables#step-2-2). So I am not entirely sure what you mean that in the history this was different for you, the instructor-led step-by-step workshops were always laid out like this.

But anyway, I am totally with you that the execution should be more or less directly after writing the very first simple playbook because it is so important. Syntax checking should be shown there as well. And that is exactly what we introduced in the [new RHEL workshop](https://github.com/ansible/workshops/blob/devel/exercises/ansible_rhel/README.md):

> Playbooks are executed using the ansible-playbook command on the control node. Before you run a new Playbook it’s a good idea to check for syntax errors:
> 
> [student<X>@ansible ansible-files]$ ansible-playbook --syntax-check apache.yml
> 
> Now you should be ready to run your Playbook:
> 
> [student<X>@ansible ansible-files]$ ansible-playbook apache.yml

[Source](https://github.com/ansible/workshops/tree/devel/exercises/ansible_rhel/1.3-playbook#step-33---running-the-playbook)

This is hopefully just what you wanted! The update will be rolled out soon, we just have to "warn" everyone first and give them some time to be prepared.

**Comment by rcpavlicek** [comment]
Unfortunately, that run command is for the SECOND playbook, the one written in exercise 3.  The one written in exercise 2 is never run.

And the history I was referring to is the one we used in Public Sector: http://redhatgov.io/workshops/ansible_tower/exercise1.2/

In that version, you write the playbook in 1.1, syntax check it and run it in 1.2, and begin the more advanced playbook in 1.3.  The current guide is missing the equivalent of 1.2.

**Comment by liquidat** [comment]
I stand corrected, you are right. Interesting that it looks like this was already missing in the first import into lightbulb. So I guess it is me who is to blame, and I am sorry for the inconvenience.

But given the fact that we will switch over to the devel branch very soon where this problem is fixed, I am not sure if it makes sense to update the current master.

@IPvSean Can you give us an update of the schedule? When will the devel branch become the new master?

**Comment by IPvSean** [comment]
@rcpavlicek we are doing a release on Monday July, 29th.  Is this fixed for your on the `devel` branch?  You can see the newly rendered page on https://ipvsean.github.io/linklight/

**Comment by IPvSean** [comment]
closing, issue been open for 8 days
