### ISSUE TITLE
Replace yum with package module (best practices)

### ISSUE THREAD

**Issue by Valien** [ansible/workshops#495]
##### SUMMARY

Replace Yum module with Package module in exercises and documentation.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- exercises

##### ADDITIONAL INFORMATION

Something I learned at Tech Exchange around Ansible best practices is to utilize the Package module vs the Yum module. That way the playbook is a little more portable among different Linux OS and package managers (Yum, Apt-Get, etc).

Any objections to updating the RHEL workshop exercises to reflect this? I can do it and submit a PR.

**Comment by liquidat** [comment]
@Valien You mean in the exercises? Which ones, can you point me to them?

**Comment by Valien** [comment]
hey @liquidat - as an example here:

https://github.com/ansible/workshops/tree/master/exercises/ansible_rhel/1.3-playbook

And in all the RHEL-based workshops/exercises when you're installing/building out the playbooks you are using Yum to do all the work. Which makes sense because the lab environments off RHPDS are RHEL-based.

But if someone tries the exercises on Ubuntu, etc. they won't work because Ubuntu uses `apt-get` vs `Yum`.

So having the exercises just use `package` instead might be better in the long run.

**Comment by liquidat** [comment]
Yes, you are right. However, this was intentional: in the exercises we want to keep things as simple as possible. The package module however is a meta module, which would at least require us to discuss that it works different on different platforms, and also that package names are not abstracted and have to provided as a variable.

To avoid that discussion detail at that stage we decided to pick the actual package module here because it is easier to understand. To nevertheless tell people about the best practices we do link a best practices deck for the RHEL workshop.
