### ISSUE TITLE
Role exercise 1.7 doesn't work unless we change the default httpd Listen port to 8080?

### ISSUE THREAD

**Issue by ffirg** [ansible/workshops#921]
##### SUMMARY

In order to configure and use Apache vhosts as in this exercise, I think we need the default httpd service listening on port 8080, not, as by default port 80.

##### ISSUE TYPE
 - Bug Report

##### CONFIGURATION

change /etc/httpd/conf/httpd.conf to
Listen 8080 (from 80)

Not sure if this is a breaking change with RHEL 8.2 nodes?

**Comment by IPvSean** [comment]
... I confirmed something is up.... digging in

**Comment by IPvSean** [comment]
hey @goetzrieger I confirmed this does not work.  I beat my head trying to figure out what is going on.... this happened right when I went on parental leave, like some different behavior.  If you do->

```
Listen 8080
```

in the vhost.conf it will work.... like somehow Listen 8080 got removed from somewhere, or somehow required... or in a previous exercise it has us add that and I am missing that ....

**Comment by IPvSean** [comment]
Looks like if you skip https://github.com/ansible/workshops/blob/e7673bfd0b77a9f5c5709b4f4bf0f0046a35a2a7/exercises/ansible_rhel/1.5-handlers/README.md

you will not be listening on 8080 which causes this problem...

I am trying to think of best solution because when I test incoming bugs I go straight to the exercise.  I like the idea of building up exercises but I need to think of how best to troubleshoot this.

**Comment by IPvSean** [comment]
OK to fix this issue i am going to do two things

- add a solution to exercise `1.5-handlers`
- add troubleshooting section to `1.7-role`
